const { logMessage } = require('./logging');

process.on('uncaughtException', (error) => {
    logMessage('error', `üî• Uncaught Exception: ${error.stack || error.message}`);
});

process.on('unhandledRejection', (reason, promise) => {
    logMessage('error', `‚ö†Ô∏è Unhandled Promise Rejection: ${reason}`);
});